# Generated by Django 6.0.3 on 2026-03-30 00:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Taille en octets')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('modality', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('structured', 'Données structurées'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extracted_content', models.TextField(blank=True, help_text='Contenu extrait du fichier')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Fichier uploadé',
                'verbose_name_plural': 'Fichiers uploadés',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('confidence', models.FloatField(default=0.0, help_text='Score de confiance (0 à 1)')),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('processing_time', models.FloatField(default=0.0, help_text='Temps de traitement en secondes')),
                ('is_fallback', models.BooleanField(default=False)),
                ('fallback_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='ingestion_app.uploadedfile')),
            ],
            options={
                'verbose_name': 'Question-Réponse',
                'verbose_name_plural': 'Questions-Réponses',
                'ordering': ['-created_at'],
            },
        ),
    ]
