# Generated by Django 6.0.4 on 2026-04-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queryresponse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='extracted_content',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='metadata',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='column_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='columns_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='extraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='image_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='row_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queryresponse',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='queryresponse',
            name='fallback_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='queryresponse',
            name='processing_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='queryresponse',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ingestion_app.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='ParsedMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='ingestion_app.uploadedfile')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('uploaded_file', 'key')},
            },
        ),
    ]
